config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'posts#index'
    resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :summary, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [ :show, :edit, :update, :destroy ]
    
    def index
        @posts = Post.all
    end
    
    def show
    end
    
    def new
        @post = Post.new
    end
    
    def create
#        if check_nil
#            render :new
#        end
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post, notice: 'Post has been created'
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render :edit
        end
    end
    
    def destroy
        @post.destroy
        redirect_to posts_path, notice: 'Post has been deleted'
    end
    
    private 
    
    def set_post
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:title, :summary, :body)
    end
    
    def check_nil
        params[:title].nil?
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Blog</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="nav">
            <%= link_to 'index', root_path %>
            <%= link_to 'posts', posts_path %>
            <%= link_to 'new post', new_post_path %>
        </div>
        
        <div id="app">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <% if notice %>
                        <div class="alert alert-success" role="alert">
                            <%= notice %>
                        </div>
                        <% end %>
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        
    </body>

</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <h5><%= t('common.errors') %></h5>
        <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="card">
    <div class="card-title">
        <h1><%= header %></h1>
    </div>
    <div class="card-text">
        <%= form_for @post do |f| %>

            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>
            </div>

            <div>
                <%= f.label :summary %>
                <%= f.text_area :summary, class: 'form-control' %>
            </div>

            <div>
                <%= f.label :body %>
                <%= f.text_area :body, class: 'form-control' %>
            </div>

            <hr>
            
            <div>
                <%= link_to 'Back', :back %>
                <%= f.submit 'Save', class: 'btn btn-primary' %>
            </div>

        <% end %>
    </div>
</div>

app/views/posts/_post.html.erb
<h2><%= link_to post.title, post_path(post) %></h2>
<p><%= post.summary %></p>
<p><small><%= post.created_at.to_date.strftime("%d %B, %Y") %></small></p>
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
<hr>

app/views/posts/edit.html.erb
<%= render 'form', header: "Edit post" %>

app/views/posts/index.html.erb
<div class="card">
    <div class="card-title">
        <h1>All posts</h1>
        <hr>
    </div>
    <div class="card-text">
        <%= render @posts %>
    </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', header: "New post" %>

app/views/posts/show.html.erb
<div class="card">
    <div class="card-title">
        <h1><%= @post.title %></h1>
    </div>
    <div class="card-text">
        <p><%= @post.body %></p>
        <hr>
        <%= link_to 'Back', :back %>
        <%= link_to 'Edit', edit_post_path(@post) %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>